// Auto-generated by hsdotnet compiler
using System;
using SuperstringSolutions.HSNet.STG;

namespace HsGenerated
{
    public static class Module
    {
        // Generated top-level bindings
        public static CLOSURE add = new FUN(CLOSURE.EMPTY, 2, (__args)=> {
    var ds_sol = __args[0];
    var ds_som = __args[1];
/* [CASESIMPLE][Alg Int] *//* I#["x_soo"] */ 
    var wild_son = STG.EVAL(ds_sol);
    var x_soo = wild_son;
    /* [CASESIMPLE][Alg Int] *//* I#["y_soq"] */ 
    var wild_sop = STG.EVAL(ds_som);
    var y_soq = wild_sop;
    /* [CASEDEFAULT][Prim IntRep] */
    var sat_sor = PRIMOPS.PlusHash(x_soo, y_soq);
    return sat_sor /* IHash */;
});

        public static CLOSURE lengthL = new FUN(CLOSURE.EMPTY, 1, (__args)=> {
    var ds_sot = __args[0];
/* [CASE][Alg List] */
    var wild_sou = STG.EVAL(ds_sot);
    switch (((CON)wild_sou).__CONSTAG__) {
        case /* Nil[] */ 1:
            return new CONPRIM<int>(0) /* IHash */;
        case /* Cons["ds_sov","xs_sow"] */ 2:
            var ds_sov = ((CON)wild_sou).Vals[0];
            var xs_sow = ((CON)wild_sou).Vals[1];
            /* [CASESIMPLE][Alg Int] *//* I#["y_soy"] */ 
            var wild_sox = STG.EVAL(STG.APPLY(lengthL, new CLOSURE[] {xs_sow}));
            var y_soy = wild_sox;
            /* [CASEDEFAULT][Prim IntRep] */
            var sat_soz = PRIMOPS.PlusHash(new CONPRIM<int>(1), y_soy);
            return sat_soz /* IHash */;
        default:
            throw new Exception("Non-exhaustive case");
    }
});

        public static CLOSURE letTest = new FUN(CLOSURE.EMPTY, 1, (__args)=> {
    var n_soB = __args[0];
/* [CASESIMPLE][Alg Int] *//* I#["x_soD"] */ 
    var wild_soC = STG.EVAL(n_soB);
    var x_soD = wild_soC;
    /* [CASEDEFAULT][Prim IntRep] */
    var sat_soF = PRIMOPS.PlusHash(x_soD, x_soD);
    /* [CASEDEFAULT][Prim IntRep] */
    var sat_soE = PRIMOPS.PlusHash(x_soD, new CONPRIM<int>(2));
    /* [CASEDEFAULT][Prim IntRep] */
    var sat_soG = PRIMOPS.PlusHash(sat_soE, sat_soF);
    return sat_soG /* IHash */;
});

        public static CLOSURE mapL = new FUN(CLOSURE.EMPTY, 2, (__args)=> {
    var ds_soI = __args[0];
    var ds_soJ = __args[1];
/* [CASE][Alg List] */
    var wild_soK = STG.EVAL(ds_soJ);
    switch (((CON)wild_soK).__CONSTAG__) {
        case /* Nil[] */ 1:
            return new CON(1, CLOSURE.EMPTY) /* Nil */;
        case /* Cons["x_soL","xs_soM"] */ 2:
            var x_soL = ((CON)wild_soK).Vals[0];
            var xs_soM = ((CON)wild_soK).Vals[1];
            
            var __fv0 = new CLOSURE[] {ds_soI, xs_soM};
            var sat_soO = new THUNK(__fv0, ()=> {
                return STG.APPLY(mapL, new CLOSURE[] {__fv0[0], __fv0[1]});
            });

            var __fv1 = new CLOSURE[] {x_soL, ds_soI};
            var sat_soN = new THUNK(__fv1, ()=> {
                return STG.APPLY(__fv1[1], new CLOSURE[] {__fv1[0]});
            });
            return new CON(2, new CLOSURE[] {sat_soN, sat_soO}) /* Cons */;
        default:
            throw new Exception("Non-exhaustive case");
    }
});

        public static CLOSURE testList_soP = new CONPRIM<int>(1); /* IHash */

        public static CLOSURE testList_soQ = new CONPRIM<int>(2); /* IHash */

        public static CLOSURE testList_soR = new CONPRIM<int>(3); /* IHash */

        public static CLOSURE @double = new FUN(CLOSURE.EMPTY, 1, (__args)=> {
    var ds_soW = __args[0];
/* [CASESIMPLE][Alg Int] *//* I#["x_soY"] */ 
    var wild_soX = STG.EVAL(ds_soW);
    var x_soY = wild_soX;
    /* [CASEDEFAULT][Prim IntRep] */
    var sat_soZ = PRIMOPS.PlusHash(x_soY, x_soY);
    return sat_soZ /* IHash */;
});

        public static CLOSURE isZero = new FUN(CLOSURE.EMPTY, 1, (__args)=> {
    var ds_sp1 = __args[0];
/* [CASESIMPLE][Alg Int] *//* I#["x_sp3"] */ 
    var wild_sp2 = STG.EVAL(ds_sp1);
    var x_sp3 = wild_sp2;
    /* [CASE][Prim IntRep] */
    var wild_sp4 = STG.EVAL(x_sp3);
    switch (((CONPRIM<int>)wild_sp4).Val) {
        case 0:
            return new CON(2, CLOSURE.EMPTY) /* True */;
        default:
            return new CON(1, CLOSURE.EMPTY) /* False */;
    }
});

        public static CLOSURE Nil = new CON(1, CLOSURE.EMPTY); /* Nil */

        public static CLOSURE testList_soS = new CON(2, new CLOSURE[] {testList_soR, Nil}); /* Cons */

        public static CLOSURE testList_soT = new CON(2, new CLOSURE[] {testList_soQ, testList_soS}); /* Cons */

        public static CLOSURE testList = new CON(2, new CLOSURE[] {testList_soP, testList_soT}); /* Cons */

        public static CLOSURE Cons = new FUN(CLOSURE.EMPTY, 2, (__args)=> {
    var eta_B0 = __args[0];
    var eta_B1 = __args[1];
    return new CON(2, new CLOSURE[] {eta_B0, eta_B1}) /* Cons */;
});


        // Entry point for testing
        public static void Main(string[] args)
        {
            // Test: add (I# 3) (I# 4)
            var r1 = STG.APPLY(add, new CLOSURE[] { new CONPRIM<int>(3), new CONPRIM<int>(4) });
            Console.WriteLine("add 3 4 = " + STG.EVAL(r1));

            // Test: lengthL testList
            var r2 = STG.APPLY(lengthL, new CLOSURE[] { testList });
            Console.WriteLine("lengthL testList = " + STG.EVAL(r2));

            // Test: double (I# 5)
            var r3 = STG.APPLY(Module.@double, new CLOSURE[] { new CONPRIM<int>(5) });
            Console.WriteLine("double 5 = " + STG.EVAL(r3));

            // Test: isZero (I# 0) and isZero (I# 1)
            var r4 = STG.APPLY(isZero, new CLOSURE[] { new CONPRIM<int>(0) });
            Console.WriteLine("isZero 0 = " + STG.EVAL(r4));
            var r5 = STG.APPLY(isZero, new CLOSURE[] { new CONPRIM<int>(1) });
            Console.WriteLine("isZero 1 = " + STG.EVAL(r5));
        }
    }
}
